### ISSUE TITLE
registerAllFlagsListener does not work on iOS with secondaryMobileKeys

### ISSUE THREAD

**Issue by emin93** [launchdarkly/react-native-client-sdk#106]
**Describe the bug**
When using `registerAllFlagsListener` with a non-default environment (`secondaryMobileKeys`), the updates are not being delivered. Switching back to the default environment fixes the issue and the updates are being delivered again.

This only happens on iOS, on Android it's working. And it does not happen when using `registerFeatureFlagListener`.

**To reproduce**
```tsx
const client = new LDClient();
client.configure(
    {
        mobileKey: 'production-key',
        secondaryMobileKeys: { test: 'test-key' },
    },
    { key: 'test-user' }
);

client.registerAllFlagsListener('example-1', console.log); // This works
client.unregisterAllFlagsListener('example-1');

client.registerAllFlagsListener('example-2', console.log, 'test'); // This does not
client.unregisterAllFlagsListener('example-2', 'test');
```

**Expected behavior**
Updates are still delivered when switching to a non-default environment using `registerAllFlagsListener`.

**SDK version**
5.1.0

**OS/platform**
iOS Simulator + real device (iPhone 13 Pro Max)

**Comment by louis-launchdarkly** [comment]
Hello @emin93, thank you for reporting this issue. We will investigate the issue to understand why this is not working.

_Filed Internally as 137002_

**Comment by louis-launchdarkly** [comment]
Hello @emin93, we think we have fixed the issue in 6.1.0, can you try it out and let us know?

**Comment by gwhelanLD** [comment]
Hi @emin93,

We hope this fix has been working for you. I'll close out this issue for now as we haven't heard back, but feel free to reopen if you're still running into the issue.

Thanks,
@gwhelanLD

**Comment by emin93** [comment]
Hi @gwhelanLD @louis-launchdarkly,

Sorry for the very late reply. I tried it out now with the latest version (`6.1.2`) and can confirm that the issue is fixed.

Thank you 👍

**Comment by besabellacyrus** [comment]
Hi hello, just using the registerAllFlagsListener app crash on ios using react native
