### ISSUE TITLE
Android: LaunchdarklyReactNativeClient.isInitialized got 2 arguments, expected 3

### ISSUE THREAD

**Issue by christophby** [launchdarkly/react-native-client-sdk#107]
**Describe the bug**
Error Message on Android
`Android: LaunchdarklyReactNativeClient.isInitialized got 2 arguments, expected 3`.
iOS works totally fine.

**To reproduce**
Call 
```
  const isInitialized = await client.isInitialized().catch(() => {
    return false; // we need to return explicitly false here. If not initialized, it returns an error
  });
```

**Expected behavior**
* No Error, should work the same like on iOS

**Logs**
<img width="400" alt="Bildschirmfoto 2022-01-11 um 18 24 00" src="https://user-images.githubusercontent.com/12933672/148991763-bb6aaed0-5046-4b50-a6c9-546c1a0c8dcf.png">

**SDK version**
React Native Client SDK 5.1.0 (currently latest)

**Language version, developer tools**
React Native

**OS/platform**
 M1 Mac, Emulator (Pixel 3A, API 32)

**Comment by louis-launchdarkly** [comment]
Hello @christophby, thank you for reaching out and reporting the issue. Let me file this onto our backlog and investigate.

Filed Internally as 138140.

**Comment by gwhelanLD** [comment]
I've done further validation with an M1 machine to verify that there wasn't an issue that only occurred on Apple Silicon, and haven't been able to replicate. My only guess as to what the issue could have been was some cached build files causing the native code to be out of sync with the JS code. As we haven't heard back, I'm closing this issue. Feel free to reopen if you're still running into this issue.

Thanks,
@gwhelanLD
