### ISSUE TITLE
No such module 'LaunchDarkly'

### ISSUE THREAD

**Issue by Lohins** [launchdarkly/react-native-client-sdk#11]
**Is this a support request?**
Yes

**Describe the bug**
I followed the guide on [this](https://docs.launchdarkly.com/docs/react-native-sdk-reference). But unable to run the project.

**To reproduce**
1. npm install --save launchdarkly-react-native-client-sdk
2. react-native link launchdarkly-react-native-client-sdk
3. add 
```
use_frameworks!
pod 'LaunchDarkly', :git => 'https://github.com/launchdarkly/ios-client.git', :tag => '3.0.0-beta.3'
```
to the `Podfile`. And `pod install`.

**Expected behavior**
`Build Successfully`.

**Result**
But I got the error:
![image](https://user-images.githubusercontent.com/9635252/59059018-48c58980-8874-11e9-9bf1-d72ff7df588a.png)

**SDK version**
`react-native`: `0.57.8`
`launchdarkly-react-native-client-sdk`: `1.0.1`
`LaunchDarkly`: `:git => 'https://github.com/launchdarkly/ios-client.git', :tag => '3.0.0-beta.3'`

**Language version, developer tools**
Xcode 10.1,

**OS/platform**
 Swift 3.

**Additional Info**
I checked the `Framework Search Paths` of `LaunchdarklyReactNativeClient.xcodeproj`:
![image](https://user-images.githubusercontent.com/9635252/59059095-80343600-8874-11e9-8324-a4be11824c90.png)

And I can find the `LaunchDarkly` under the `Pods` folder.

**Comment by torchhound** [comment]
React Native has several bugs in 0.57 on iOS and you have to manually link binaries to the React pod, your project workspace, and your test project workspace. Here are some links to the possible bugs: [Link JS.core](https://github.com/facebook/react-native/issues/23183) and [Link glog and Double Conversion](https://github.com/facebook/react-native/issues/23390). The [hello-react-native ios workspace](https://github.com/launchdarkly/hello-react-native/tree/master/ios) has all of the correct libraries linked.

**Comment by Lohins** [comment]
Sorry, I didn't use React in Pod. I import it in the Libraries.

**Comment by torchhound** [comment]
Hi @Lohins I'm not sure if our SDK will work without Cocoapods. We haven't done any testing on that type of setup. You will likely still need to manually link glog and Double Conversion.

**Comment by phuochau** [comment]
@torchhound @Lohins did you find the solution? I have same issue as well and trying to fix

**Comment by shercoder** [comment]
Anyone found the solution to how to integrate this library without having to bring in React via Podfile?

I tried just add ing `pod 'LaunchDarkly', '4.1.2'` to our `Podfile` and then followed the [manual linking steps](https://facebook.github.io/react-native/docs/0.59/linking-libraries-ios#manual-linking) to bring in the `launchdarkly-react-native-client-sdk`. 

I am still getting this error `No such module 'LaunchDarkly'`
