### ISSUE TITLE
Impossible to turn an anonymous user with an automatically generated key to a non-anonymous user.

### ISSUE THREAD

**Issue by andreaSimonePorceddu** [launchdarkly/react-native-client-sdk#111]
**Describe the bug**

We are initializing the user without passing any key, so, we let the SDK generate one, in this way: 
```typescript
LDClient.configure(configuration, { })
```
> This means the user will be initialized as anonymous.

---
After the user logins we use the identify method in order to change the anonymous to false and set some custom parameters:
```typescript
LDClient.identify({ anonymous: false, custom: { userId }})
```
It seems that the changes are not handled and the user still remains an anonymous user

**To reproduce**
As in description

**Expected behaviour**
The user should be turned to non-anonymous

**Logs**
([["user": ["anonymous": true, "custom": ["device": "iPhone13,2", "os": "15.2", "customerId": asYiSDUAAXo7U6JjSkKzKH], "key": "773D6E7E-9DBE-489B-9A45-7D4AD7C78EE8"], "creationDate": 1643297299063, "kind": "identify", "key": "773D6E7E-9DBE-489B-9A45-7D4AD7C78EE8"], ["key": "773D6E7E-9DBE-489B-9A45-7D4AD7C78EE8", "user": ["key": "773D6E7E-9DBE-489B-9A45-7D4AD7C78EE8", "anonymous": true, "custom": ["os": "15.2", "customerId": "xxxxxxxxxx", "device": "iPhone13,2"]], "kind": "identify", "creationDate": 1643297299760]])

**SDK version**
5.1.1

**Language version, developer tools**
React native 0.65.1

**OS/platform**
OS/Android

**Additional Context**
We tried also the alias method with the same result

**Comment by louis-launchdarkly** [comment]
Hello @andreaSimonePorceddu, based on the logic of the React Native SDK 5.1.1 change, the determination of the user is anonymous or not is determined by the `key` attribute in the user object. https://github.com/launchdarkly/react-native-client-sdk/blob/master/index.d.ts#L201-L206

So to call identify and make it not anonymous, you will need something like:
`LDClient.identify({ anonymous: false, key: userId , custom: { userId }})`

Or is your intention here is to tie the events before you have the userId and after you have the usedId together under the same user?

**Comment by andreaSimonePorceddu** [comment]
> 

Hey @louis-launchdarkly, I would like to let launch darkly to generate the userKey and then make the same generated user( with the same key) not anonymous after the user login.
Are there any ways to do that?

**Comment by shaddeen** [comment]
@louis-launchdarkly If the SDK is already generating the key for us, shouldn't we able to retain this key and set the `anonymous` flag to `true` when they are logged in? Otherwise we're doubling our MAU. Our alternative is to generate a uuid ourselves and pass it directly as the key ourselves.

**Comment by louis-launchdarkly** [comment]
Hello @andreaSimonePorceddu and @shaddeen, for this use case, we understand that if the first `configure` call has no user key as an argument (e.g. `{}`), there is no method to get the key back. For this use case to tie the same user before and after user login, for now, I would recommend the following:

1. Generate a random key from your application (instead of relying on the auto-generation).
2. When the app user logins, create an [alias](https://github.com/launchdarkly/react-native-client-sdk/blob/9b387650b4057ef388c0c58452fed93cdd465c51/index.js#L203) event to mark the anonymous user and the login user as the same user. This ability is added when we release [5.0.0 Changelog](https://github.com/launchdarkly/react-native-client-sdk/blob/3f84e875bbadd3eb41dc49350568b46b97655328/CHANGELOG.md#added-1)
3. Here is the [documentation](https://docs.launchdarkly.com/sdk/features/aliasing-users) of the feature. Thanks to this issue report, we realized the docs have not been updated with the React Native support. We will fix that.

@shaddeen, I hear your question about MAU, and I will check with the team and provide an answer afterward.

**Comment by louis-launchdarkly** [comment]
Hello @shaddeen, I have checked with the team and the documentation about MAU. Here is the part about an anonymous user: https://docs.launchdarkly.com/home/users/anonymous-users#understanding-how-anonymous-users-contribute-to-mau

In a nutshell, MAU is tracked by the user key. So if you have a different key for each anonymous user, that will each count as a separate user for MAU purposes. To avoid ballooning the MAU, we recommend using a single key for all anonymous users. However, this suggestion is orthogonal to what @andreaSimonePorceddu wants to do in this case - so currently, you can either use a single anonymous user to save MAU or generate a key for each anonymous user but will use more MAU.

Hope that answers your question.

**Comment by wojteg1337** [comment]
Hello

I'm trying to proceed with A/B test for anonymous user and keep `feature flag` value in signed user. I'm self generating key for that anonymous user after sign up i make `alias` call to merge those users, I do the call to read flag value and it's not the same as for my anonymous user. Am I missing something in my implementation or how can I keep the value of that anonymous user?

**Comment by louis-launchdarkly** [comment]
Hello @wojteg1337, 

Would you mind opening a support ticket with us? We may need to ask you for a sample of your code, and potentially look at your flags in your organization to understand your issue, hence it will be much easier to communicate through Support.

**Comment by louis-launchdarkly** [comment]
For other developers who may search up this thread in the future, https://docs.launchdarkly.com/sdk/features/user-config#anonymous-user-attributes-in-the-react-native-sdk is the link to the documentation on how we recommend using anonymous users.

Given all questions are replied to in this thread, I am closing this. Please feel free to reach out to Support or create a new issue if you have any questions.
