### ISSUE TITLE
Integration with Expo Modules for expo managed apps

### ISSUE THREAD

**Issue by bkasten-rbi** [launchdarkly/react-native-client-sdk#114]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `launchdarkly-react-native-client-sdk@5.1.0` for the project I'm working on.

I'm using this within an `expo` project. Expo has some heuristics it will use to automatically install react-native code into it's managed build. I've found that if I simply include a `app.config.js` with a function, expo will treat this module as a valid expo module to include in it's build. 

Hoping you would be open to including this!

```js
// launchdarkly-react-native-client-sdk/app.config.js
module.exports = config => config;
```

**Comment by bkasten-rbi** [comment]
I think this is actually not necessary anymore :) Sorry!

**Comment by masiamj** [comment]
@bkasten-rbi Were you able to use this package via the Expo managed workflow? Did you end up writing a custom config plugin?
