### ISSUE TITLE
Compatibility with Xcode 10.2.1 and React Native 0.59

### ISSUE THREAD

**Issue by torchhound** [launchdarkly/react-native-client-sdk#12]
The next release of the React Native client SDK will include update compatibility with newer versions of Xcode, React, and React Native.

**Comment by jwilliamson-qb** [comment]
Hey @torchhound -- when is this release scheduled?

**Comment by torchhound** [comment]
Hi @jwilliamson-qb we discovered a bug while testing this release. We have a solution and the next React Native release should be out very soon.

**Comment by torchhound** [comment]
@jwilliamson-qb React Native Client 2.0.0 was just released and contains compatibility for Xcode 10.2.1 and React Native 0.59.9
