### ISSUE TITLE
Add support for react native 0.68

### ISSUE THREAD

**Issue by AlexanderEggers** [launchdarkly/react-native-client-sdk#130]
**Is your feature request related to a problem? Please describe.**
React native published the stable version of 0.68. I noticed that this library excludes support for that version - but there is actually no reason for that. Of course the new architecture won't work, but at least the old one should still work without issues.

**Describe the solution you'd like**
Update the peerDependencies (and any other needed changes) to support react native 0.68 officially.

**Comment by louis-launchdarkly** [comment]
Hello @AlexanderEggers, thank you for reaching out to us and letting us know RN 0.68 now has a stable version. Because we will need to update the test to run against the new environment, we can't immediately pick up your PR. I will provide another update when we finish testing the change.

**Comment by louis-launchdarkly** [comment]
As a quick update, from the testing on our private mirror, it seems RN 0.68 is working fine with the current RN SDK code. We are going to cut a release for that, and I will give you another update when LaunchDarkly's official RN 0.68 support is released.

**Comment by louis-launchdarkly** [comment]
Added the support for RN 0.68 in [6.1.3](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.1.3).
