### ISSUE TITLE
Updating from 4.2.2 to Latest (6.1.2) makes flag evaluation fail silently

### ISSUE THREAD

**Issue by krizzu** [launchdarkly/react-native-client-sdk#133]
**Describe the bug**
I'm preparing an app to target Android SDK 31, so I bumped LD to latest version. I adjusted all breaking changes in code, so went on manual testing flag changes via LD dashboard. In my User Panel, I toggle boolean flag to explicitly set `true/false` for given user. But every time I check flag value using `detail evaluation`, it fallbacks to default. I tracked it down to [reason value inside Native Module here](https://github.com/launchdarkly/react-native-client-sdk/blob/b4539a8964e20d5dda7daf8be3b7715f4d4eb801/android/src/main/java/com/launchdarkly/reactnative/LaunchdarklyReactNativeClientModule.java#L438). In my case, the `reason` is `null`, which is not checked in code.

SS from debugging (I've added my patch-package to cover this case):
![Screen Shot 2022-04-11 at 17 05 06](https://user-images.githubusercontent.com/6444719/162769900-3327ce12-b256-4ea4-b49a-736d2039edbc.png)

**To reproduce**
In my case, it was:

1. Set a listener for all flags
2. Go to your user dashboard in web LD 
3. Change flag value for selected user
4. allFlagListener is triggered with default value, 

**Expected behavior**
Flag should be evaluated with a reason.

**Logs**
The result of detailed evaluation on JS side:
```
{"errorKind": "EXCEPTION", "kind": "ERROR", "value": false}
```

Logcat log:
```
D/com.launchdarkly.eventsource.EventParser: [c.l.eventsource.EventParser line] Parsing line: data:{"key":"isAutoPayMandatory","version":199,"flagVersion":91,"value":true,"variation":0,"trackEvents":false}
```

**SDK version**
RN 6.1.2

**OS/platform**
Running on Samsung A51, Android 12.

**Comment by louis-launchdarkly** [comment]
Hello @krizzu, thank you for reporting the issue. I am able to reproduce the issue locally and we will work on a fix for this. I will give you an update when we make progress on the fix.

Filed Internally as 149512

**Comment by louis-launchdarkly** [comment]
Hello @krizzu, while we don't have a fix yet (we need to check the behavior to make sure we line up both Android and iOS), here is more information.

LaunchDarkly doesn't always send the evaluation reason back for bandwidth and performance reasons. Like your debugging snippet, we need to make sure the code handles that correctly. If this blocks your development right now, while we don't recommend doing that in production, as a temporary workaround you can enable the `evaluationReasons` config to make sure the SDK receives the detail during development. https://github.com/launchdarkly/react-native-client-sdk/blob/6.1.2/index.d.ts#L148

We will provide another update when we have a fix in an internal review.

**Comment by louis-launchdarkly** [comment]
@krizzu - We just released a fix for this in https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.1.3

Please try it out and let us know how it goes.
