### ISSUE TITLE
isInitialized returns false when reopening a minimized/suspended app on Android 11 and then breaks

### ISSUE THREAD

**Issue by fmedinac** [launchdarkly/react-native-client-sdk#137]
**Describe the bug**
On Android 11 and below, when the app gets reopened, `client.isInitialized()` returns `false`, but `client.configure()` throws an already initialized error, preventing any upcoming code to proceed in the function that called it.

This is not reproducible in Android 12, as apps get suspended, keeping their states.

**To reproduce**
- Add the following code to `App.js`

```
const getLaunchDarklyFlags = async () => {
  const isInitialized = await client.isInitialized();

  console.log('LD isInitialized", isInitialized);

  if (isInitialized) {
    return;
  }

  const userId = DeviceInfo.getDeviceId();

  const user = {
    key: userId,
  };

  client.configure(config, user);

  const allLaunchDarklyFlags = await client.allFlags();
  console.log('LD allLaunchDarklyFlags", allLaunchDarklyFlags);

  return allLaunchDarklyFlags;
};

const App = () => {
  const [featureFlags, setFeatureFlags] = useState();

  useEffect(() => {
    getLaunchDarklyFlags()
      .then((flags) => setFeatureFlags(flags))
      .catch((e) =>
        console.warn('getLaunchDarklyFlags: failed to getAllFlags', e),
      );
  }, []);

  return <View />
}
```

- On Android 10 or 11, open the app
- Use the back-arrow key or gesture to minimize the app
- Reopen the app

**Expected behavior**
We see `LD isInitialized true` in Metro terminal
We see `LD allLaunchDarklyFlags{ flag1: true }` in Metro terminal

**Actual result**
`LD isInitialized false` is printed
`Warning: Client has already been initialized` is printed
`LD allLaunchDarklyFlags{ flag1: true }` is never printed

**SDK version**
4.1.2

**OS/platform**
Android 11

**Additional context**
LaunchDarkly has not been terminated (client.close()) in the example above so we can test this scenario.

A workaround that worked for us was wrapping `client.configure(config, user);` in a `try {} catch {}` 🤷‍♂️

**Comment by louis-launchdarkly** [comment]
Hello @fmedinac, thank you for reporting the issue. We know the React and the Native state could get detached from hot reloading because of LaunchDarkly's usage of the native modules. But this is the first time I hear about the difference between different versions of Android.

To decide on the next step, do you mind answering a couple of questions? 
- If you wrap the `client.configure(config, user);` in a `try {} catch {}` block, does the `client.allFlags()` in your code works after reopening the app?
- When you say the SDK version is 4.1.2, do you actually mean 6.1.2?
- Is this on an emulator or a real device?

**Comment by fmedinac** [comment]
> - If you wrap the client.configure(config, user); in a try {} catch {} block, does the client.allFlags() in your code works after reopening the app?

Yes, placing it inside a try/catch it does work.

> - When you say the SDK version is 4.1.2, do you actually mean 6.1.2?

Good point, I don't know exactly why, but we have `4.1.2` set on our project. I was the one to blame adding it while ago so I will try to update it to 6.x.x up and see if everything works.

> - Is this on an emulator or a real device?

Real devices

**Comment by manurodriguezDL** [comment]
Hello, any updated on this? @fmedinac did you manage to solve this bug?
Im having the same issue on my app. Im running LaunchDarkly's latest version.

@louis-launchdarkly can you provide a "correct way" to initialize the client on react native? 
This is the code Im running:
This is the code Im using right now:

```
    if (await isInitialized()) {
      await client.identify(user)
    } else {
      await client.configure(config, user)
    }
```

where isInitialized() is just:
```
  try {
    const isInit = await client.isInitialized()
    return isInit
  } catch {
    // client was not initialized, ignore promise rejection
  }
  return false
```

Thanks.

**Comment by louis-launchdarkly** [comment]
Hello @fmedinac and @manurodriguezDL - I am really sorry that it took a while as we were working on the RN 0.71 support and the Contexts support in RN SDK (and fixing a lot of existing RN SDK issues) before able to get back to this.

We have a ManualTestApp that demos the init process https://github.com/launchdarkly/react-native-client-sdk/blob/main/ManualTestApp/App.tsx#L30 (when the client is null, instantiate and call configure on it - as `isInitialized()` in the SDK is showing the state of SDK initialized with LaunchDarkly, not just the initialize is call.)

If there is anything else that we can help with, please feel free to reach out to us via https://support.launchdarkly.com/hc/en-us - Support will be the quickest way to get help.
