### ISSUE TITLE
SDK causes dev build failed to reload in dev menu

### ISSUE THREAD

**Issue by normanzb** [launchdarkly/react-native-client-sdk#138]
**Is this a support request?**
No

**Describe the bug**
In react native app it allows you to reload the app by using dev menu. 

however when doing this with an app instantiated LaunchDarkly it throws error: 

`LaunchDarkly SDK already initialized`

**To reproduce**
1. Build an app that runs LaunchDarkly react native sdk.
2. Run the app in dev mode
3. Shake your phone to bring up dev menu
4. Tap refresh

**Expected behavior**
App refreshes without problem

**Logs**
Error: LaunchDarkly SDK already initialized

**SDK version**
6.1.3

**Language version, developer tools**
react native 0.64

**OS/platform**
iOS 14

**Additional context**
Implement `onCatalystInstanceDestroy` and `invalidate` in bridge module and properly dispose previous client instance

**Comment by louis-launchdarkly** [comment]
Hello @normanzb, thank you for the suggestion. What you mentioned sounds promising, but let me chat with the team and give your suggestion a try first. I will give you an update afterward.

**Comment by louis-launchdarkly** [comment]
Hello @normanzb, in the meantime, you can just catch the error and proceed for now - as long as you are not trying to reconfigure the LDClient with a different config, the LDClient is still up and will work correctly fetching feature flag information.

**Comment by AdamTyler** [comment]
@louis-launchdarkly I am running into the same issue mentioned above.

Based on your comment you say I should be able to run correctly, but how can I fetch a feature flag without a reference to the running LDClient? 

I couldn't find any way in the docs to get a reference to the already configured client instance so that I can run something like `ldClient.boolVariation()`

**Comment by louis-launchdarkly** [comment]
Hello @AdamTyler, sorry for the late reply. We recently published the updated react-native sample app here: https://github.com/launchdarkly/hello-react-native which may provide some hints on best practices.

If your particular question is about hot reloading (when the `LDClient` on the native module is still floating around), based on this portion of the code: https://github.com/launchdarkly/react-native-client-sdk/blob/main/index.js#L25 - it is possible to call 
```
      let ldClient = new LDClient();
      try {
        await ldClient.configure(config, user);
      } catch (err) {
        console.log(err);
      }
```
And start using `ldClient` after that even if you get the 'LaunchDarkly SDK already initialized' error. This error should not show up on your customer's application unless you enable some sort of "hot reloading the whole mobile application" behavior on the user side.

**Comment by swushi** [comment]
Hi, coworker of @AdamTyler.

We were able to fix this by closing out the client before doing any initialization. 

```js
let ldClient = new LDClient();
ldClient.close(); // this line fixes the issue
try {
  await ldClient.configure(config, user);
} catch (err) {
  console.log(err);
}
```

**Comment by seaBubble** [comment]
This issue is still occurring, is there a plan to fix it or a workaround? Ignoring the error is not enough, this is causing noise that could be masking real initialisation errors and also generating a lot of noise in error reporting tools.

**Comment by louis-launchdarkly** [comment]
Hello @seaBubble, sorry for the late reply as the team had been focusing on the React Native SDK 7.x release with support for RN 0.71. In this major release, we have reworked the SDK, and the ManualTestApps that come in this repo are more stable now. Can you try to follow the initialization pattern in the [ManualTestApp ](https://github.com/launchdarkly/react-native-client-sdk/blob/main/ManualTestApp/App.tsx#L67) And see does that fix your issue now?

**Comment by louis-launchdarkly** [comment]
Tested this with the latest RN SDK 7.x and this is still an issue. Marking this as an enhancement. This will likely be solved if we move to a more JavaScript-based implementation going forward, but we don't have a concrete plan or a timeline for a more JavaScript-based implementation yet.

**Comment by yusinto** [comment]
The react-native SDK have been re-written and [released](https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react-native). The new version v10 is purely in TypeScript and supports Expo. Please consider upgrading to that new version to fix this issue. Thank you for your patience.
