### ISSUE TITLE
error:  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by Marcuspo** [launchdarkly/react-native-client-sdk#139]
**Describe the bug**
I installed the sdk and now I want to run in the simulator but it shows this error.

`error:  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
    `

**To reproduce**
Only run in iOs

**SDK version**

    "launchdarkly-react-native-client-sdk": "^6.1.3",

**Language version, developer tools**
Javascript.
React Native

**OS/platform**
MacOs.

**Comment by Marcuspo** [comment]
`async function useLaunchDarkly(userProfile) {
  try {
    const client = new LDClient();
    const config = { mobileKey: LAUNCHDARKLY_MOBILE_KEY };
    const user = {
      key: 'teste',
    };
  } catch (error) {
    console.log('error: ', error);
  }
}

export default useLaunchDarkly;`

this is configs

**Comment by Marcuspo** [comment]
![Captura de Tela 2022-04-27 às 11 08 12](https://user-images.githubusercontent.com/17353066/165537822-4c94d801-b28a-48cf-b80a-54cbeb32feb9.png)

Error in constructor.

"react-native": "0.65.1",
"launchdarkly-react-native-client-sdk": "^6.1.3",

**Comment by louis-launchdarkly** [comment]
Hello @Marcuspo, thank you for reaching out. While we are looking at your issue, can you try and see can you run the ManualTestApp that comes with this repository? https://github.com/launchdarkly/react-native-client-sdk/tree/6.1.3/ManualTestApp

**Comment by aar0n1998** [comment]
@Marcuspo how were you able to solve the `Invariant Violation: new NativeEventEmitter() requires a non-null argument` error? We are using
```
"react-native": "0.66.3",
"launchdarkly-react-native-client-sdk": "^6.1.3"
```

**Comment by louis-launchdarkly** [comment]
@Marcuspo, Sorry for the late reply. I am not sure I understand your question - the `client.setOnline` and `client.setOffline` method is a wrapper to call the native Android or iOS SDK behind the scene (https://github.com/launchdarkly/react-native-client-sdk/blob/6.2.0/index.js#L127-L137), so I don't think that anything to do with the React `useEffect` hook.

**Comment by louis-launchdarkly** [comment]
Hello @aar0n1998, we recently updated our sample application at https://github.com/launchdarkly/hello-react-native, I hope that will provide hints for you to debug your issue.

**Comment by aar0n1998** [comment]
Thank you @louis-launchdarkly for the reference. I will have a look 😄

**Comment by louis-launchdarkly** [comment]
Closing after a month of no new updates. If there is any issue about this, please feel free to reach out to LaunchDarkly Support or open a new issue.
