### ISSUE TITLE
Build fail on M1 arm64 architecture

### ISSUE THREAD

**Issue by mmeksasi** [launchdarkly/react-native-client-sdk#140]
Hello, when I run npx react-native run ios I'm getting the following error build fail : 
**CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'launchdarkly-react-native-client-sdk' from project 'Pods') PhaseScriptExecution**

I'm using 
React Native v0.67.4
launchdarkly-react-native-client-sdk: v6.1.3

device:
Simulator Iphone 13 ios15.4

xCode v13.3.1

I can run the project from xCode because I'm running using Rosetta but can't run the project from the terminal getting the following error If someone have an idea

**Comment by louis-launchdarkly** [comment]
Hello @mmeksasi, thank you for reaching out, we will need to try this out and we will give you an update afterward.

_Filed Internally as 151358_

**Comment by louis-launchdarkly** [comment]
As a quick update, the developer that has an M1 machine is trying to set this up to reproduce the issue.

**Comment by cwaldren-ld** [comment]
Hi @mmeksasi , I'm wondering if your issue has been resolved, or if it is still not working for you?

I tested with the following configuration on M1.

```
XCode: v13.3.1
React Native: v0.67.4
Simulator: iPhone 13 (iOS 15.2)
launchdarkly-react-native-client-sdk: v6.2.0
```

I did not encounter a build failure using `npx yarn run ios`.

**Comment by louis-launchdarkly** [comment]
Closing this with no response from the customer after a month.
