### ISSUE TITLE
Support for React Native version 0.69

### ISSUE THREAD

**Issue by hsandhu** [launchdarkly/react-native-client-sdk#149]
When can we expect the SDK to support React Native 0.69?

**Comment by louis-launchdarkly** [comment]
Hello @hsandhu, thank you for checking - we just released support for RN 0.69 today (SDK version [6.2.2](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.2.2))! If you are targeting iOS, please look at the CircleCI build to see which combination of RN and Xcode we test and verified will work correctly.
