### ISSUE TITLE
Support for react-native .70

### ISSUE THREAD

**Issue by mfelix5** [launchdarkly/react-native-client-sdk#153]
Hello, is there a plan or timeline for supporting react-native .70? Thank you!

**Comment by louis-launchdarkly** [comment]
Hello @mfelix5, thank you for the reminder. I verified that the RN SDK code as is work with RN 0.70.1 (and Xcode 14.0.1), but we will need a bit more time to finish cutting the release. I will update this request again when we cut the release and the change is available to public.

**Comment by louis-launchdarkly** [comment]
Hello @mfelix5, we just released https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.2.3 which has a test to verify the RN SDK is working correctly with the RN 0.70 version. If there is any other request, please let us know either via Support request or by opening another issue.

**Comment by mfelix5** [comment]
Thank you!
