### ISSUE TITLE
App with RN 0.63.3 crashes after installing lib in version 5.1.1

### ISSUE THREAD

**Issue by felipejoribeiro** [launchdarkly/react-native-client-sdk#156]
**Describe the bug**
I installed version 5.1.1, in my app, as recommended for 0.63.3 SDK, but after installing the app keeps crashing, and it doesn't open. After uninstalling the lib, I'm able to open the app in the emulator again.

**Expected behavior**
The emulator should open normally with the lib working.

**Logs**
```json
{"DONE": 4, "HEADERS_RECEIVED": 2, "LOADING": 3, "OPENED": 1, "UNSENT": 0, "_aborted": false, "_cachedResponse": undefined, "_hasError": true, "_headers": {"accept": "application/json, text/plain, */*", "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36"}, "_incrementalEvents": false, "_lowerCaseResponseHeaders": {}, "_method": "GET", "_perfKey": "network_XMLHttpRequest_https://play.google.com/store/apps/details?id=com.snackin&hl=us", "_requestId": null, "_response": "canceled due to java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in /data/app/com.snackin-DkiuJo851oslvZXexZj2RA==/base.apk!classes3.dex)", "_responseType": "", "_sent": true, "_subscriptions": [], "_timedOut": false, "_trackingName": "unknown", "_url": "https://play.google.com/store/apps/details?id=com.snackin&hl=us", "data": undefined, "readyState": 4, "responseHeaders": undefined, "status": 0, "timeout": 0, "upload": {}, "withCredentials": true}

```
**SDK version**
5.1.1

**Language version, developer tools**
yarn 1.22.28;
node version 14.19.1;
react 16.13.1;
react-native 0.63.3;

**OS/platform**
Apple Monterey 12.6

**Comment by louis-launchdarkly** [comment]
Hello @felipejoribeiro, I have filed this internally as 171835.

While we are going to try looking into this issue, I am also wondering if would it be possible for you to upgrade your react native version. There are stability improvements that we released in the RN SDK 6.x, and that if you can upgrade to RN 0.65 minimum you will be able to get those.

**Comment by felipejoribeiro** [comment]
Thank you for the prompt response. I shouldn't be able to do it in time for testing within the 14 trial period. Our company's big project requires some attention before the upgrade.

**Comment by yusinto** [comment]
@felipejoribeiro is this still an issue? Please try upgrading to the latest version [7.1.1](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/7.1.1) to verify.
