### ISSUE TITLE
6.2.3 is completely broken on Android

### ISSUE THREAD

**Issue by i1skn** [launchdarkly/react-native-client-sdk#157]
**Describe the bug**
6.2.3 is completely broken for Android

**To reproduce**
Launch `ManualTestApp` on Android using 6.2.3
Observe in console ` ERROR  [Error: LaunchDarkly SDK already initialized]` immediately after run.

**Expected behavior**
Calling `.configure(...)` should not resolve into an `LaunchDarkly SDK already initialized` error neither at the start of the app, nor after we call `.close()` and then `.configure(...)` again.

**SDK version**
6.2.3

**OS/platform**
Android 12

**Additional context**
This happens because `.isInitialized(...)` used to return a rejected Promise, when client is not available and since 6.2.3 (as pointed [here](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.2.3)) it resolves with `false`. 

If you look on the code below, you'll see, that if `.isInitialized(...)` is not rejected -> we throw an error, but right we do not reject it, hence we see a vicious cycle. 

On 6.2.2 `.isInitialized(...)` would resolve with `false` after you've called `.close()` instead of rejecting (see [here](https://github.com/launchdarkly/android-client-sdk/issues/186) this issue).

So, 6.2.3 is completely unusable on Android.

https://github.com/launchdarkly/react-native-client-sdk/blob/0754d67ccb6c308633b1081e19f938546bc54bec/index.js#L21-L43

**Comment by mfelix5** [comment]
Same issue.

**Comment by louis-launchdarkly** [comment]
Hello @i1skn and @mfelix5, thank you for reporting this issue - this is a serious issue and we are looking into it - for unblocking the people using this, we are looking to first revert this part of the `isInitialized` change to provide a leapfrogged  6.2.4 first and have a separate fix for how `isInitialized` is used. Before we have a fix, please pin to use 6.2.2 for now.
 
We will update this when we have a release.

**Comment by louis-launchdarkly** [comment]
Hello @i1skn and @mfelix5, we have just released the fix as 6.2.4. Please test this out and let us know if there is anything else.

**Comment by i1skn** [comment]
@louis-launchdarkly thanks so much for such a quick fix! Seems like both issues were fixed in 6.2.4!
