### ISSUE TITLE
Update react-native peer dependency for v 6.2.3

### ISSUE THREAD

**Issue by mfelix5** [launchdarkly/react-native-client-sdk#158]
**Describe the bug**
Installing v 6.2.3 with react-native v .70 results in this warning: 
`launchdarkly-react-native-client-sdk@6.2.3" has incorrect peer dependency "react-native@>=0.64.0 <0.70.0"`

**To reproduce**
Install v 6.23 with react-native v .70

**Expected behavior**
No warning

**Additional context**
Should probably be updated here: https://github.com/launchdarkly/react-native-client-sdk/blob/0754d67ccb6c308633b1081e19f938546bc54bec/package.json#L26

**Comment by louis-launchdarkly** [comment]
Hello @mfelix5, thank you for reporting this. We updated the package.json to reflect RN 0.70.x is supported and we have a CircleCI test to verify that. Please let us know if there is any other issue.
