### ISSUE TITLE
Update User Properties after configuration

### ISSUE THREAD

**Issue by an-kumar** [launchdarkly/react-native-client-sdk#17]
**Is your feature request related to a problem? Please describe.**
I want a way to update user properties after configuring the client.

**Describe the solution you'd like**
Just like the e.g ios SDK's updateUser

**Describe alternatives you've considered**
I don't know of an alternative, is there any way to do this at the moment?

**Comment by torchhound** [comment]
Hi @an-kumar please see [our React Native Client SDK documentation on the `identify` method and how to change users.](https://docs.launchdarkly.com/docs/react-native-sdk-reference#section-identify)

**Comment by huanvu** [comment]
@torchhound I'm having some sort issue with the identify function iOS and this particular use case. Shortly after calling configure, I call identify to update user properties. This works fine on android, but on iOS, I end up with incorrect (seemingly cached) flag values. I did noticed with a bit of debugging that after calling identify, setOnline is set to false for whatever reason.

**Comment by torchhound** [comment]
@huanvu that is correct behavior for the iOS SDK. The iOS SDK has a backoff on `setOnline` calls so an SDK cannot spam LaunchDarkly with flag refresh requests. `identify` calls `setOnline` false to guarantee fresh flag values.

**Comment by torchhound** [comment]
@an-kumar I am closing this issue for now, please comment here or reach out to LaunchDarkly Support if you need additional assistance.
