### ISSUE TITLE
React Native 0.71 Support

### ISSUE THREAD

**Issue by holospeed** [launchdarkly/react-native-client-sdk#173]
**The problem**
The SDK is not working with the latest RN minor version ( 0.71 ). 

**The solution**
I would like to use the SDK with the latest RN version.

**Alternatives**
There is no alternative, which is why the company bought the license.

**Comment by louis-launchdarkly** [comment]
Hello @holospeed, thank you for reaching out. We are currently in the process of preparing the next React Native SDK major version, and that should have RN 0.71 support. We do not have the exact date yet, and I can give an update when we have an ETA for the release.

**Comment by tmadej** [comment]
This is a blocker for us as well. Paid license. I suspect you will be getting a lot of people now that 0.71.2 is out and expo 48 is in beta. 

Is there a pre-release hot fix that will get us unblocked?

**Comment by lorenzoangelini** [comment]
@louis-launchdarkly it would perfect if was released a 6.3.1, with the support for react native 0.71. I think that it should be an emergency to make your library available for the last stable release.

**Comment by louis-launchdarkly** [comment]
Hello @tmadej and @lorenzoangelini, I hear your concern and we understand the interest as we already see a lot of people looking at this issue. The team is currently working on the next major version of RN SDK that will support Contexts. We aim to release the work for Contexts first and will take on upgrading to support RN 0.71 as the immediate next minor release afterward, as upgrading to support RN 0.71 is a non-trivial amount of work.

We also understand the hope to get this as a 6.x minor update. However, the current 6.x supports down to RN 0.64, and the older version of RN is slowing down our uptake of new RN releases. So we may not be able to provide a 6.x SDK that is compatible with RN 0.71, even when getting 0.71 support is a top priority.

**Comment by mfelix5** [comment]
We're in the same position with our efforts to upgrade to react-native 0.71 blocked until this is resolved. Thank you for prioritizing this.

**Comment by idov-softserve** [comment]
@louis-launchdarkly Sorry for rechecking, but let me clarify this: does your comment mean that RN 0.71 will only be supported by Context-based version of LD SDK? And in order to use it, we'll have to revise the current LD implementation too?

Or is it possible to have RN 0.71 support in SDK that doesn't support Contexts?

And yes, it would be really great to have at least some approximate ETA. Our biggest concern is, of all the other external services and libraries used in our project, LD is **the only blocker** for RN 0.71 update - and we have no idea when it's expected to be resolved.

**Comment by chernandezlt** [comment]
Any solutions here? I have the same problem with React Native 0.71.2

**Comment by hwekim** [comment]
any update on RN > 0.71 support?

**Comment by gakinson** [comment]
+1

**Comment by louis-launchdarkly** [comment]
Hello all, really sorry for the delayed response. As you all may have noticed, we released the 7.x RN SDK last Friday. At this point, getting RN 0.71 is the immediate priority of LaunchDarkly, and we will give more frequent updates on this ticket. I will post another update on Friday giving a concrete ETA.

@idov-softserve While the 7.x React Native SDK is going to be Context-based, the logic is backward compatible (i.e. The user you create will transparently convert to a user context and will work with the existing rules that you have).

**Comment by louis-launchdarkly** [comment]
We are working on the update and support for RN 0.71 should be coming in about two weeks. I will give another update by end of next week or if there is any release before the end of next week.

**Comment by louis-launchdarkly** [comment]
Hello all, LaunchDarkly has released https://github.com/launchdarkly/react-native-client-sdk/releases/tag/7.1.1 today supporting RN 0.71. Once again, sorry that this collided with the Context work and took us a while for releasing the support. 

If you are using RN SDK 6.x, please follow the [migration guide](https://docs.launchdarkly.com/sdk/client-side/react/react-native-migration-6-to-7) to upgrade to 7.x. While we highly encourage you all to give Contexts a try, there is backward compatibility built in, so flag rules working with only the user will work correctly if you provide the same user object, even after you upgrade.
