### ISSUE TITLE
I can't build React Native Android app after installing LaunchDarkly SDK

### ISSUE THREAD

**Issue by akkadaya** [launchdarkly/react-native-client-sdk#174]
**Describe the bug**
I can't build React Native Android app after installing LaunchDarkly SDK

**To reproduce**
Run 
```
npx react-native run-android
```
**Expected behavior**
Build Android app successfully

**Logs**
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launchdarkly-react-native-client-sdk:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':launchdarkly-react-native-client-sdk:debugCompileClasspath'.
   > Could not find any matches for com.facebook.react:react-native:0.70.+ as no versions of com.facebook.react:react-native are available.
     Required by:
         project :launchdarkly-react-native-client-sdk
```

**SDK version**
the latest
```
    "launchdarkly-react-native-client-sdk": "^6.3.0",
```

**Language version, developer tools**
- React Native 0.70.6 
- TypeScript

**OS/platform**
MacOS 13.2

**Comment by akkadaya** [comment]
I had custom configurations in `build.gradle` which was affecting the `com.facebook.react:react-native` dependency

Will close the issue

**Comment by TheAlmightyBob** [comment]
@akkadaya Can you share what custom configuration was the problem? I'm seeing this same error

**Comment by menttys** [comment]
@akkadaya @TheAlmightyBob what was the `build.gradle` configurations affecting it? Thanks!

**Comment by NazarKuryl0** [comment]
@akkadaya Can you share what custom configuration was the problem? I'm seeing this same error. Is this error related to next part in build.gradle?
```
exclusiveContent {
          filter {
              includeGroup "com.facebook.react"
          }
          forRepository {
              maven {
                  url "$rootDir/../node_modules/react-native/android"
              }
          }
      }
```
If yes, what could be done, if i need to keep that part of code in build.gradle?
