### ISSUE TITLE
Compatibility with React Native 0.60+

### ISSUE THREAD

**Issue by theonetheycallneo** [launchdarkly/react-native-client-sdk#18]
**Is your feature request related to a problem? Please describe.**

I would love to see the SDK support React-Native 0.60+

**Describe the solution you'd like**

We were forced to upgrade to React-Native 0.60 due to the Google Play Android restrictions now enforcing 64bit as of Aug 1 2019:
https://developer.android.com/distribute/best-practices/develop/64-bit

**Describe alternatives you've considered**
We have integrated the lib correctly but seeing errors listed below.
We are considering forking the library and making the modifications to support:
https://github.com/FreebirdRides/react-native-client-sdk

**Additional context**

Debug runtime error:
There's an error with React bridge when hot reloading a feature flag:
![Screenshot_9_12_19__4_10_PM](https://user-images.githubusercontent.com/367806/64827103-de5d6d00-d577-11e9-89c5-947b5e64ea34.png)

Release build error:
❌  ld: library not found for -lLaunchdarklyReactNativeClient

**Comment by bwoskow-ld** [comment]
React Native 0.61 was released earlier today. Stay tuned for an updated LaunchDarkly SDK version -- we'll update here when a new version is available.

**Comment by harrisrobin** [comment]
@bwoskow-ld, let us know if there is anything we can do to help here 👍 

Would love to see this 🎉

**Comment by torchhound** [comment]
Hi all, version 2.0.2 was just released with support for React Native 0.61.2.

**Comment by theonetheycallneo** [comment]
Thanks guy!
