### ISSUE TITLE
Attempt to invoke virtual method 'java.util.Map.com.launchDarkly.android.LDClient.allFlags()' on a null object reference 

### ISSUE THREAD

**Issue by ethanneff** [launchdarkly/react-native-client-sdk#19]
How can I fix this error?

![Screenshot_20190920-070546](https://user-images.githubusercontent.com/2933593/65333464-6d204a00-db75-11e9-9900-936a81dd8925.png)

**Comment by ethanneff** [comment]
Happens when there are no feature flags on the dashboard

**Comment by torchhound** [comment]
Hi @ethanneff thanks for reporting this, glad you solved this issue. We recommend using the promise returned by `configure` which ensures that `LDClient` is ready to use with fresh flag values.
