### ISSUE TITLE
Function to register listener for all flags

### ISSUE THREAD

**Issue by jojofeng** [launchdarkly/react-native-client-sdk#21]
**Is your feature request related to a problem? Please describe.**
I would love to have a function that can listen and respond in real time to changes to any flag, instead of having to create individual listeners for specific flags with `registerFeatureFlagListener`.

**Describe the solution you'd like**
A function (`registerAllFlagsListener`, like what is mentioned [here](http://launchdarkly.github.io/android-client-sdk/com/launchdarkly/android/flagstore/FlagStoreManager.html#registerAllFlagsListener-com.launchdarkly.android.LDAllFlagsListener-)) that takes a callback to be called upon receiving a change to any and all of my feature flags.

**Describe alternatives you've considered**
Creating individual listeners with `registerFeatureFlagListener` for each flag key in an array. Would like to be able to rig my app up to respond to all flags without having to do that tedious work.

Thank you for all your hard work!

**Comment by torchhound** [comment]
Hi @jojofeng thanks for the feature request! This feature is on the roadmap, stay tuned for a future release.

**Comment by torchhound** [comment]
Hi @jojofeng this feature just shipped as part of the 2.1.0 release. It works very similarly to the existing feature flag listeners, hope this further enables your workflow!

**Comment by jojofeng** [comment]
Thank you very much! glad to hear this. wondering if it is also available for the React client-side SDK?

**Comment by bwoskow-ld** [comment]
Hi @jojofeng,

We're glad to hear that this functionality is working for you in the React Native SDK. 

As for your latest question -- the React SDK is built on top of the JavaScript SDK which means that all functionality exposed by the JavaScript SDK is also accessible to customers of the React SDK. Take a look at the JS SDK's [change listener functionality](https://docs.launchdarkly.com/docs/js-sdk-reference#section-subscribing-to-feature-flag-changes). You can use that functionality by accessing the underlying `ldclient` as described in the [React SDK docs](https://docs.launchdarkly.com/docs/react-sdk-reference).
