### ISSUE TITLE
Webpack 5: Should not import the named export 'version'

### ISSUE THREAD

**Issue by theParthe** [launchdarkly/react-native-client-sdk#210]
**Describe the bug**
Webpack 5 throws a warning with the way version is imported in index.js

**To reproduce**
Try to use webpack@^5.0.0

**Expected behavior**
Webpack should not throw warnings

**Logs**
warn  - ../../node_modules/launchdarkly-react-native-client-sdk/index.js
Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)

**SDK version**
"launchdarkly-react-client-sdk": "^2.26.0",

**Language version, developer tools**
Node v16.17.0

**OS/platform**
MacOS Ventura Version 13.2.1 (22D68)

**Comment by louis-launchdarkly** [comment]
Responded to the open PR.

**Comment by yusinto** [comment]
Closing because this sounds like a PR for the react sdk not the react native sdk.
