### ISSUE TITLE
Error on pod install: "The following Swift pods cannot yet be integrated as static libraries:  The Swift pod `LaunchDarkly` depends upon `DarklyEventSource`, which does not define modules"

### ISSUE THREAD

**Issue by hkellaway** [launchdarkly/react-native-client-sdk#22]
**Is this a support request?**
No

**Describe the bug**
When following integration instructions for the SDK, the `pod install` step fails with the following error:

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `LaunchDarkly` depends upon `DarklyEventSource`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

**To reproduce**

Within a React Native project:

* `yarn add launchdarkly-react-native-client-sdk`
* `cd ios/`
* `pod install`

**Expected behavior**
When integrating the LaunchDarkly SDK for React Native apps, installing the requisite pods should succeed.

**Logs**
N/A

**SDK version**
I am using the latest as of the time of writing - version `2.0.2`

**Language version, developer tools**
React Native version `0.61.1`
CocoaPods version `1.8.3`

**OS/platform**
MacOS Mojave 10.14.5

**Additional context**

Thank you!

**Comment by hkellaway** [comment]
For those encountering this issue, I was able to get around it by doing the following:

* Fork the [DarklyEventSource repo](https://github.com/launchdarkly/ios-eventsource)
* Update its podspec to include `'DEFINES_MODULE' => 'YES'` in the `xcconfig` set
Example: [hkellaway/ios-eventsource#3e5a9c6db6af3b243b8f573c21ae9981f0bae273](https://github.com/hkellaway/ios-eventsource/commit/3e5a9c6db6af3b243b8f573c21ae9981f0bae273)
* Update your React Native `ios/Podfile` to include `pod 'DarklyEventSource', :git => "git@github.com:YOUR_FORK_NAME/ios-eventsource.git", :branch => "master"`

This solution was inspired by this thread: https://github.com/ReactiveX/RxSwift/issues/1800
And its fix here: https://github.com/ReactiveX/RxSwift/commit/5f5790de918406d7f01acdaa7e79d6daba18c1a7

**Comment by hkellaway** [comment]
i do see that the official docs say to include `LaunchDarkly` explicitly in the Podfile and with the `use_frameworks` declaration; while that works, it's out-of-line with how React Native projects default to being set up. namely, React Native doesn't default to making you include `use_frameworks` and you don't generally include third-party library pods explicitly (RN searches for third-party podspecs and will automatically include them). it'd be nice not to have to requires frameworks just because one is using LaunchDarkly.

so, while there is an official solution to this error - i'd like to understand if there's a specific reason not to update `DarklyEventSource` instead?

**Comment by torchhound** [comment]
Hi @hkellaway, thanks for reporting this! Moving the LaunchDarkly iOS SDK away from `use_frameworks` is on the roadmap. Our documentation for React Native currently shows `use_frameworks!` in the Podfile. Thank you for surfacing this solution.

**Comment by hkellaway** [comment]
appreciate the response

**Comment by torchhound** [comment]
We are also tracking the request to remove `use_frameworks` in this [issue](https://github.com/launchdarkly/react-native-client-sdk/issues/13).
