### ISSUE TITLE
iOS app crashes when receiving flag update events, only after reload in debug mode

### ISSUE THREAD

**Issue by robinheinze** [launchdarkly/react-native-client-sdk#222]
Note: Please read the context section at the bottom. 

**Describe the bug**
When running the app in debug mode, and `ldClient.registerAllFlagsListener` has been called, the app crashes when receiving events. This only occurs after the app has been reloaded at least once. 

**To reproduce**
- Run an app with the LauchDarkly SDK installed (in debug mode)
- Register the all flags listener with `registerAllFlagsListener` when the app loads. 

In app.tsx:

```
let allFlagsListenerId = 0
useEffect(() => {
    const listenerId = allFlagsListenerId.toString()
    allFlagsListenerId++
    ldClient.registerAllFlagsListener(listenerId, ()=> console.log('flags updated'))
  
    return () => ldClient.unregisterAllFlagsListener(listenerId)
  }, [])
```

- Change the value of a flag using LaunchDarkly account dashboard
- App does not crash
- Reload the app
- Change the value of the flag again
- App crashes  with the following error:

<img width="1341" alt="Screen Shot 2023-06-08 at 2 23 11 PM" src="https://github.com/launchdarkly/react-native-client-sdk/assets/6894653/db4830a6-59f5-460e-8b46-d08a7522e475">

**Expected behavior**
- Event is received with no crash

**Logs**
N/A

**SDK version**
7.1.4

**Language version, developer tools**
`npx react-native info` output

```
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 961.81 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**OS/platform**
macOS 12.6.3

**Additional context**

This seems similar to #38 but that was fixed back in v3. This seems like a different issue because it crashes when the event is received, rather than when the listener is registered. 

It also could have something to do with, https://github.com/facebook/react-native/issues/34105. When I follow the person's instructions, I receive similar results where the value of _callableJSModules is fluctuating between nil not nil very rapidly.

**Comment by louis-launchdarkly** [comment]
Hello @robinheinze, thank you for reaching out. Is this the React Native hot reload capability? We have heads issues before where the hot reload doesn't reload the native portion, so we want to know is this the same class of issues.

Also, does this work on Android (or also crashing there)?

**Comment by robinheinze** [comment]
The issue does not occur when the app is hot reloaded, only full reload. As far as I've been able to tell, this is only iOS, not android.

**Comment by louis-launchdarkly** [comment]
Seems like the depending issue (https://github.com/facebook/react-native/issues/34105) is still open on the react-native main code branch as I checked today.

**Comment by rsomlette** [comment]
My app keep crashing every times I would play with some flags but at least I now know why, hot reload seems to be the culprit.
But just like #166, #110 would most likely fix it.
Anyway at least it doesn't happen in prod environment

**Comment by yusinto** [comment]
The react-native SDK have been re-written and [released](https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react-native). The new version v10 is purely in TypeScript and supports Expo. Please consider upgrading to that new version to fix this issue. Thank you for your patience.
