### ISSUE TITLE
v8.0.0 crashes on startup - iOS

### ISSUE THREAD

**Issue by mfelix5** [launchdarkly/react-native-client-sdk#234]
**Describe the bug**
Updating the ld sdk from v7.1.4 to v8.0.0 causes the app to crash on startup. This happens when trying to configure a new LDClient with a very basic `config` (just the mobileKey) and `context` (just a key). `LDClient.configure(config, context)` works as expected with v7.1.4 and works as expected on Android using v8.0.0. Specifying a timeout or changing the context type doesn't appear to affect the issue.

**Logs**
<img width="1157" alt="Screenshot 2023-09-08 at 8 18 58 AM" src="https://github.com/launchdarkly/react-native-client-sdk/assets/33203734/fa6a9fda-d545-4255-8a20-5e9f246ea60c">

**SDK version**
v8.0.0

**Language version, developer tools**
React Native v0.71.7

**OS/platform**
iOS

**Comment by louis-launchdarkly** [comment]
Hello @ mfelix5, could you provide us a snippet of your start-up code, especially with the context? We suspected the removal of the deprecated `LDUser` which we documented [here](https://docs.launchdarkly.com/sdk/client-side/react/migration-7-to-8-react-native) is what is causing the issue, and we will look into updating the documentation to address that.

**Comment by mfelix5** [comment]
Thanks for pointing out this documentation. I did not see it previously and I'm sure that is the problem.
