### ISSUE TITLE
0.73 support

### ISSUE THREAD

**Issue by DominicTobias** [launchdarkly/react-native-client-sdk#237]
Hi, this is a feature request for 0.73. The recently released latest stable version of RN.

**Comment by louis-launchdarkly** [comment]
Hello @DominicTobias, thank you for reaching out. We are working on the build to make sure the SDK code is compatible with RN 0.73.

**Comment by DominicTobias** [comment]
Thanks, I guess no need to keep this open!

**Comment by louis-launchdarkly** [comment]
As a quick update for people who follow this, we are working through the issue that RN 0.73 completely removed support for Java 11. We are still actively working on this.

**Comment by mark-quinn** [comment]
@louis-launchdarkly am I right in saying that the latest version now supports RN 0.73?
