### ISSUE TITLE
xcode 15.1 - underlying Objective-C module 'LDSwiftEventSource' not found

### ISSUE THREAD

**Issue by JeffKGabriel** [launchdarkly/react-native-client-sdk#239]
**Describe the bug**
xcode 15.1 build error:

LDSwiftEventSource.private.swiftinterface
line1 :  failed to verify module interface of 'LDSwiftEventSource' 
line6 : underlying Objective-C module 'LDSwiftEventSource' not found

LDSwiftEventSource.swiftinterface
line1 :  failed to verify module interface of 'LDSwiftEventSource' 
line6 : underlying Objective-C module 'LDSwiftEventSource' not found

(same 2 errors come from both LDSwiftEventSource & .private)

**To reproduce**
i have tried to even use the 8.1.0 release branch as it states it is prepared for xcode 15.1 [sonoma 14.2 macos forces 15.1 :') ]

ie package.json
"launchdarkly-react-native-client-sdk": "git://github.com/launchdarkly/react-native-client-sdk.git#77edf0f16c45f8f9e8167ad88767da678fa480e7",
(current commit hash of /tree/release-8.1.0)

**SDK version**
my podfile.lock includes
- LaunchDarkly (9.1.1):
    - LaunchDarkly/Core (= 9.1.1)
  - launchdarkly-react-native-client-sdk (8.0.1):
    - LaunchDarkly (= 9.1.1)
    - React-Core
  - LaunchDarkly/Core (9.1.1):
    - LDSwiftEventSource (= 3.1.1)
  - LDSwiftEventSource (3.1.1)
  
  **package.json of release-8.1.0 branch still has v 8.0.1 (i think thats why it still shows up as 8.0.1, not sure)

**OS/platform**
MacOS Sonoma 14.2

upgraded from 7.1.1 to 8.0.1 to try to fix xcode 15.1 build errors, nothing yet-
Sonoma 14.2 os was updated overnight automatically, so is unfortunate, might downgrade back to previous macOS if have too,

Let me know if im overlooking something, or something to try

**Comment by louis-launchdarkly** [comment]
Hello @JeffKGabriel, thank you for reporting the issue - we will update the build test and verify before getting back to you.

**Comment by louis-launchdarkly** [comment]
We just released v8.0.2, with the CircleCI test updated to use their Xcode 15.1.0 image. The test didn't show any issue: https://github.com/launchdarkly/react-native-client-sdk/runs/19838059832 - So I am not sure can LaunchDarkly helps here

Have you tried to clean your project before rebuilding the application?

**Comment by JeffKGabriel** [comment]
Hmm okay thanks- i will check circleCI build for any differences here

Yes to clean & even remove ~/Library/Developer/Xcode/DerivedData and ~/Library/Caches/CocoaPods

Will poke around and let you know- thanks!
