### ISSUE TITLE
Build fails: Undefined symbol

### ISSUE THREAD

**Issue by froston** [launchdarkly/react-native-client-sdk#30]
**Describe the bug**
The build fails and gives me 100 errors, all of them starting with `Undefined symbol: ...`.

**To reproduce**
1. Install `LaunchDarklySDK` following the steps in the [Getting Started guide](https://docs.launchdarkly.com/docs/react-native-sdk-reference#section-getting-started)
2. Build the app.

I found [similar issue on StackOverflow](https://stackoverflow.com/questions/57903395/about-100-error-in-xcode-undefined-symbols-for-architecture-x86-64-upgraded-re)

**Expected behavior**
Should make the build with success and SDK working in the app.

**versions**
launchdarkly-react-native-client-sdk  2.1.0
macOS Catalina 10.15.2
Xcode 11.3

**Additional context**
![Log](https://user-images.githubusercontent.com/24678624/71521737-bbde2e00-28a0-11ea-856f-3b4b5b430bc7.png)

Thanks for any help!

**Comment by Titozzz** [comment]
Still unable to build without use_frameworks! with 2.1.0 too :/

**Comment by froston** [comment]
@Titozzz didn't try  `use_frameworks!` now it works, thanks!

**Comment by torchhound** [comment]
Hi all, I'm still working on the documentation but to fix the undefined symbols error create a new, empty Swift file and then accept the prompt for an Objective C bridging header file. This should fix the error.

**Comment by torchhound** [comment]
@froston @Titozzz Are both of you using iOS SDK version 4.3.2 in your Podfile?

**Comment by Titozzz** [comment]
@torchhound Yeah I'm aware of the trick to build Swift with the empty file.
Yes I'm using 4.3.2

**Comment by froston** [comment]
@torchhound Me too I'm using 4.3.2

**Comment by Titozzz** [comment]
(can confirm both of the tricks work)

**Comment by torchhound** [comment]
What is the 2nd trick? Did the Objective C bridging header fix the undefined symbol error? @Titozzz
