### ISSUE TITLE
[Android] Client was already initialized error

### ISSUE THREAD

**Issue by haakandev** [launchdarkly/react-native-client-sdk#40]
**Describe the bug**
I believe there's an issue when the App Context is alive but Activity Context has been destroyed (difference on Android explained [here](https://wix.github.io/react-native-navigation/#/docs/app-launch?id=the-difference-between-the-platforms)). As the JS side is trying to initialize/configure the LD client along with the UI, this seems to cause a conflict. My guess is that the client is still around within the Application Context?
The font change in the reproduction steps below is intended as a short-cut to destroy the UI/Activity Context.

This is somewhat related to #10, but here an actual issue rather than a 'nice to have' I think.

**To reproduce**
1. Download & set up the hello world project as described: https://github.com/launchdarkly/hello-react-native
2. Run on Android (I've been using emulator)
3. With the app running on the device/emulator, navigate to device Settings > Display > Font size
4. Change the font size
5. Return to the hello world app

**Expected behavior**
The app to be able to re-create the activity context.

**SDK version**
2.2.0

**Language version, developer tools**
React Native 0.61.2

**OS/platform**
Android 9

**Screenshot**
![Screenshot_1581987723](https://user-images.githubusercontent.com/30954044/74695016-8cb3bf80-5246-11ea-9583-01ffe8d47840.png)

**Comment by torchhound** [comment]
Hi @haakandev thanks for reporting this. Are you seeing this error in your application or only in the `hello-react-native` application? Is this more of a dev/hot reload issue or is this an issue affecting production code?

**Comment by haakandev** [comment]
Hi @torchhound - thanks for the reply.
First encountered it in my own application, but figured using the sample application was a simple case for reproduction.
Gave it a try in release mode, and didn't have an issue. 
Running it in debug mode but with fast refresh disabled still saw the issue occur.

In my own project I've 'promoted' the client to module scope to keep it alive, which seems to dodge this issue while developing. But would be nice if this wasn't required.

**Comment by sam1463** [comment]
I am also running into this on android. It happens when calling client.configure on android more than once in a running application. Is this not permitted? My use case is that there are multiple backend environments which are accessible by the same UI, so for parts of the app for a user who is not logged in, we use the LaunchDarkly key for the production environment, but if the user logs in to a different backend environment, we call client.configure with the appropriate client config for that environment. That works fine on iOS but hits this error on android.

**Comment by torchhound** [comment]
@sam1463 `client.configure` is not meant to be called multiple times. Multi-environment support is coming to React Native soon. This feature enables exactly the sort of workflow you are describing. As it stands right now I think what you are doing is undefined behavior.

**Comment by sam1463** [comment]
@torchhound ok thanks. How soon do you think it'll be ready? Just looking for an order of magnitude like next few days/weeks vs a few months vs a year or more

**Comment by torchhound** [comment]
@sam1463 ballpark estimate of months but no promises. We are aware that many devs are interested in this feature.

**Comment by haakandev** [comment]
Any updates/progress on this?

After upgrading to RN 0.62.2 (launchdarkly-react-native-client-sdk@3.1.2) I'm getting this issue again in dev mode. This despite the work-around in my [previous comment](https://github.com/launchdarkly/react-native-client-sdk/issues/40#issuecomment-588005411). It makes development painful... 

Slightly different error log:
![Screenshot_1594815201](https://user-images.githubusercontent.com/30954044/87543660-740ddf80-c6e8-11ea-8cc4-403d100c5689.png)

**Comment by davemarquess** [comment]
hi there - any updates on this? still seeing this error in dev mode on Android with RN 0.63.4 
(launchdarkly-react-native-client-sdk@3.2.1)

**Comment by bwoskow-ld** [comment]
We're actively working on some dependencies which need to be resolved before we bring the multi-environment feature to the React Native SDK. We expect to circle back to this early in the new year.

**Comment by davemarquess** [comment]
Ok i see, thanks for the update @bwoskow-ld. And was curious:
> the multi-environment feature to the React Native SDK.
^ does this mean the LD React Native SDK only currently works on iOS?

**Comment by bwoskow-ld** [comment]
No, the React Native SDK works on both iOS and Android. See [the repository readme](https://github.com/launchdarkly/react-native-client-sdk#supported-versions) for information about our supported versions.

**Comment by Ali-Ayyad** [comment]
Any update on this issue ? Im running into the same error when i exit the app using the android back button. Even though im using LDClient.close() and .flush() and unregisteringFlagListeners before the app exiting. If i kill the app and open it again this issue doesn't show up.

**Comment by torchhound** [comment]
The React Native SDK will no longer allow `configure` to be called if the SDK is already initialized. It does not error and will reject the promise if the SDK is already initialized.

**Comment by mharrisweb** [comment]
Getting the same error, is there a fix for this using:

"launchdarkly-react-native-client-sdk": "3.2.2" and "react-native": "0.62.0" ?
