### ISSUE TITLE
Support for Xcode 11

### ISSUE THREAD

**Issue by Lohins** [launchdarkly/react-native-client-sdk#43]
**Is your feature request related to a problem? Please describe.**
Given the words from Apple Store: `Starting April, 2020, all apps submitted to the App Store will need to be built with Xcode 11. Xcode 11 requires macOS Mojave 10.14.3 or later.`

**Describe the solution you'd like**
Do you plan to release a SDK before the deadline ( April, 2020).

**Comment by bwoskow-ld** [comment]
Hi @Lohins ,

The SDK should work up to Xcode 11.3, although the SDK is not explicitly tested against those versions at this time. It is currently tested against 10.2.1.

I filed an internal task for our engineering team to update our testing to use Xcode 11 and to update the readme to reflect as much.

If you encounter or have encountered issues, please contact our support team at support@launchdarkly.com with the details.

**Comment by Lohins** [comment]
> Hi @Lohins ,
> 
> The SDK should work up to Xcode 11.3, although the SDK is not explicitly tested against those versions at this time. It is currently tested against 10.2.1.
> 
> I filed an internal task for our engineering team to update our testing to use Xcode 11 and to update the readme to reflect as much.
> 
> If you encounter or have encountered issues, please contact our support team at [support@launchdarkly.com](mailto:support@launchdarkly.com) with the details.

Thanks so much for your reply.
