### ISSUE TITLE
Unable to build on iOS

### ISSUE THREAD

**Issue by jwilliamson-qb** [launchdarkly/react-native-client-sdk#5]
Hi all,
Congrats on the 1.0.0 release! Really appreciate the hard work.

**Describe the bug**
When running `pod install` I get this error:
```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `LaunchDarkly` depends upon `DarklyEventSource`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `LaunchdarklyReactNativeClient` depends upon `React`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

When building in Xcode I get these errors:
```
warning: no rule to process file '/Users/jwilliamson/Developer/QBMobile/node_modules/launchdarkly-react-native-client/ios/LaunchdarklyReactNativeClient-Bridging-Header.h' of type sourcecode.c.h for architecture x86_64
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.
```

**To reproduce**
Follow the installation instructions [here](https://docs.launchdarkly.com/docs/react-native-sdk-reference) and the readme [here](https://github.com/launchdarkly/react-native-client-sdk)

**Expected behavior**
Should be able to build successfully using Xcode or `react-native run-ios`

**Logs**
See above

**SDK version**
1.0.0

**Language version, developer tools**
React Native

**OS/platform**
iOS

**Comment by BG687** [comment]
Excited to integrate `1.0.0`, congrats! 

I also ran into this issue, and addressed it by setting `:modular_headers => true` on React and LaunchDarkly. However, I now get a bunch of compilation errors in the LD RN Client, starting with: 

`Use of undeclared type 'LDObserverOwner'` in LaunchdarklyReactNativeClient.swift line 7 

<img width="988" alt="Screen Shot 2019-04-26 at 3 17 09 PM" src="https://user-images.githubusercontent.com/19270780/56831047-1d438e00-6836-11e9-8447-00aa7ef0bff6.png">

**Comment by torchhound** [comment]
@BG687 you probably need to update your Podfile to `pod 'LaunchDarkly', :git => 'https://github.com/launchdarkly/ios-client.git', :tag => '3.0.0-beta.3'`. The observer owner naming changed between `beta.2` and `beta.3`.

@jwilliamson-qb I believe this is caused by an incompatible version of Xcode. Currently, our SDK is only compatible with Xcode 10.1/Swift 3. Our iOS SDK has been updated to Xcode 10.2 and that will be added to React Native in version 1.1.

**Comment by jwilliamson-qb** [comment]
Thanks @torchhound. You might consider mentioning the Xcode 10.1 dependency on the Readme to help others.

**Comment by siddhantbenadikar** [comment]
@torchhound when can we expect the release 1.1 to be out?

**Comment by torchhound** [comment]
@siddhantbenadikar React Native Client SDK version 2.0.0 is currently in testing. We've bumped React Native to 0.59.3, React to 16.8.3, Swift to 5.0, Xcode to 10.2.1, Android Client SDK to 2.8.1, and iOS Client SDK to 4.0.0. That release should be out soon.
