### ISSUE TITLE
Add Provider Wrapper like in launchdarkly-react-client-sdk

### ISSUE THREAD

**Issue by azai91** [launchdarkly/react-native-client-sdk#53]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
Will there be plans to add a Provider API for react native like there is for the regular react sdk.

```
import { withLDProvider } from 'launchdarkly-react-client-sdk';
```

**Describe alternatives you've considered**
N/A

**Additional context**
Add any other context about the feature request here.

**Comment by torchhound** [comment]
Hi @azai91, we do not currently have plans for a Provider API.

*Filed internally as 79104*

**Comment by LucasEThomas** [comment]
I wrote a wrapper library that provides a wrapper and some really ergonomic hooks. My team has been using it in our production Android app for a couple months now. Caveat: only one instance of the wrapper is currently supported at this point, so you won't be able to wrap different portions of your app with different LD contexts... yet...

https://www.npmjs.com/package/launch-darkly-react-native-client-factory

**Comment by yusinto** [comment]
The react-native SDK has been re-written and [released](https://github.com/launchdarkly/js-core/tree/main/packages/sdk/react-native). The new version v10 is purely in TypeScript and supports Expo. Its APIs are based on the JS SDK and the React SDK and includes LDProvider and hooks. Read the [docs](https://docs.launchdarkly.com/sdk/client-side/react/react-native#getting-started), here's a preview:

```tsx
const client = new ReactNativeLDClient('mobile-key-123abc', AutoEnvAttributes.Enabled, options);
const context = { kind: 'user', key: 'user-key-123abc' }

const App = () => {
  // call identify on App mount or later in some other component
  useEffect(() => {
    client.identify(context).catch((e: any) => console.log(e));
  }, []);

  return (
    <LDProvider client={client}>
      <YourComponent />
    </LDProvider>
  );
};

export default App;

```

Please consider upgrading to v10. Thank you for your patience.
