### ISSUE TITLE
Can't find variable: promise

### ISSUE THREAD

**Issue by ramakula** [launchdarkly/react-native-client-sdk#55]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
When calling isInitialized to see if it is initialized on Android, we are getting "can't find variable. promise" And yes it is missing

**To reproduce**
Call isInitialized on ldClient instance
**Expected behavior**
Please define promise and fix it.

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
3.2.0

**Language version, developer tools**
Java, Android
<img width="1430" alt="Screen Shot 2020-08-25 at 7 58 01 PM" src="https://user-images.githubusercontent.com/2745769/91250335-a2ca9d00-e70d-11ea-9258-e3b9721d35e1.png">

**OS/platform**
Android

**Additional context**

**Comment by bwoskow-ld** [comment]
Hi @ramakula ,

You're right -- `isInitialized` isn't working as currently implemented. Sorry about that; when looking at the code now it is obvious that it won't work. We'll have this fixed shortly.

**Comment by ramakula** [comment]
@bwoskow-ld Thank you. Looking forward to the fix. We were trying to use it to avoid 100s null pointer exception we are seeing on our android app. This is resulting in hard crashes on our android app. We suspect they might be due to calling identify when initialize is in progress(it is on background thread.) And it is happening only on android.  Please let me know if I should go ahead and file a separate ticket. It is always good to have null check in identify method in LaunchdarklyReactNativeClientModule. We would rather have identify fail than
![Screen Shot 2020-08-26 at 4 17 19 PM](https://user-images.githubusercontent.com/2745769/91366237-0ad5bd80-e7b8-11ea-8151-61f2b9008832.png)
![Screen Shot 2020-08-26 at 4 16 46 PM](https://user-images.githubusercontent.com/2745769/91366276-26d95f00-e7b8-11ea-9416-6f6978a07307.png)

 app crashing with null pointer exception.

**Comment by bwoskow-ld** [comment]
The fix for your originally reported issue will be out within the next hour. I'll file an internal ticket about null checks.

**Comment by ramakula** [comment]
Thank you very much. Appreciate prompt response.

**Comment by bwoskow-ld** [comment]
Upgrade to [3.2.1](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/3.2.1) for the fix.

**Comment by ramakula** [comment]
> The fix for your originally reported issue will be out within the next hour. I'll file an internal ticket about null checks.

Any luck on this internal ticket to get null checks in?

**Comment by bwoskow-ld** [comment]
The ticket to add null checks is on our backlog but not a priority at the moment.

**Comment by ramakula** [comment]
Please let us know if the ticket to have null check is fixed by any chance. We are seeing our app crashing 10s of times every week because of these lack of null checks. We are on version 3.1.0.

**Comment by bwoskow-ld** [comment]
> We are on version 3.1.0.

@ramakula -- please upgrade to version 3.2.1. Back in August of last year we released a patch version to fix your originally reported issue. Once on version 3.2.1+ you can call `isInitialized` on Android to ensure that you're only calling other `LDClient` methods when the underlying Android client is initialized. Alternatively you can `await` your `configure` call to ensure that the the LaunchDarkly client is initialized.

As mentioned before, the null checks are on our backlog but not a priority, as there are two viable workarounds in place right now. We'll consider this for inclusion in a React Native SDK project we plan on starting soon. In the meantime though, we recommend that you upgrade to the version including the fix for your originally-reported issue.

**Comment by ramakula** [comment]
Ah great. Thank you.

**Comment by bwoskow-ld** [comment]
@ramakula in addition to the prior fix in version 3.2.1, yesterday's 4.0.0 release addresses your concerns about the null checks.

**Comment by ramakula** [comment]
Oh great thank you @bwoskow-ld
