### ISSUE TITLE
Upgrade The Version for LaunchDarkly

### ISSUE THREAD

**Issue by cj768025549** [launchdarkly/react-native-client-sdk#65]
I found the LaunchDarkly version for react-native does not update for a long time. Even the react-native version updates, but the dependence for iOS doesn't update. Is there a plan to update it ? The version is 4.5.0 now.
![截屏2021-03-18 上午9 08 32](https://user-images.githubusercontent.com/3918091/111558443-b92f6780-87c9-11eb-8251-3f0be051a755.png)

**Comment by bwoskow-ld** [comment]
We are actively working on an updated version right now and will have a release out by the end of March. Stay tuned! We'll update this issue once it is available.

**Comment by torchhound** [comment]
Hi @cj768025549 LaunchDarkly iOS has been updated to 5.4.0 in React Native version 4.0 released today.
