### ISSUE TITLE
React Native 0.64 support

### ISSUE THREAD

**Issue by Chrischuck** [launchdarkly/react-native-client-sdk#69]
On another issue it was mentioned another release w/ react native 0.64 support would be out fairly soon after 4.0.0 release.

Would you be able to provide an eta for it? Thanks!

**Comment by bwoskow-ld** [comment]
Hi @Chrischuck ,

We're actively working on a bug fix and adding React Native 0.64 compatibility. Look for the added compatibility in a 4.1.0 SDK release in the next 1-2 weeks. We'll update this ticket when it is available.

Cheers,
@bwoskow-ld

**Comment by torchhound** [comment]
Hi @Chrischuck React Native 0.64 compatibility is now available in SDK version 4.1.0.

**Comment by Chrischuck** [comment]
@torchhound @bwoskow-ld Thank you guys for the quick turnaround!!
