### ISSUE TITLE
Major issue with version 4.2.X

### ISSUE THREAD

**Issue by Titozzz** [launchdarkly/react-native-client-sdk#82]
**Describe the bug**
The refactor that happened in 4.2.0 introduced a lot of broken code in some function for example registerAllFlagsListeners where you access undeclared variables flagKey. What happened guys ?

**To reproduce**
Either read the code and see you use non existing variables here for example https://github.com/launchdarkly/react-native-client-sdk/blob/master/index.js#L321
Or call these function and crash

**Expected behavior**
...

**SDK version**
4.2.0 or 4.2.1

**Comment by bwoskow-ld** [comment]
Thanks for reporting this @Titozzz. We'll get the undeclared variable usages fixed shortly, and will work to ensure that we don't release such issues moving forward.

**Comment by gwhelanLD** [comment]
Hi @Titozzz,

This issue should be fixed in the 4.2.2 release. 

Thanks again for the report,
@gwhelanLD
