### ISSUE TITLE
Apps using this SDK cannot be installed on Android 12 devices

### ISSUE THREAD

**Issue by emilioicai** [launchdarkly/react-native-client-sdk#85]
**Describe the bug**
From [Android Documentation](https://developer.android.com/about/versions/12/behavior-changes-12): 

**If your app targets Android 12 and contains activities, services, or broadcast receivers that use intent filters, you must explicitly declare the android:exported attribute for these app components.**

launchdarkly-react-native-client-sdk depends on launchdarkly-android-client-sdk 2.14.1 which doesn't include this attribute (it was added on [launchdarkly-android-client-sdk  3.0.1](https://github.com/launchdarkly/android-client-sdk/pull/132))

**To reproduce**
Install an app targeting Android 12 and using launchdarkly-react-native-client-sdk => App can't be installed

**Expected behavior**
The app installs properly on Android 12 devices

**OS/platform**
Android 12

**Comment by bwoskow-ld** [comment]
Hi @emilioicai ,

We have some changes on our private SDK repository mirror to bump the `launchdarkly-android-client-sdk` dependency to a sufficiently new version. We'll keep this issue open until those changes are available in a new React Native SDK version, and will update here when that's the case.

Cheers,
@bwoskow-ld

**Comment by gwhelanLD** [comment]
Hi @emilioicai,

This is addressed in the new [5.0.0 release](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/5.0.0). Thanks for the issue report, I'm going to close this now that a fix has been released.

Thanks,
@gwhelanLD
