### ISSUE TITLE
Configuring the client doesn't return if user is offline

### ISSUE THREAD

**Issue by haakandev** [launchdarkly/react-native-client-sdk#88]
**Describe the bug**
The `.configure()` call on the client never returns or throws if the user is offline.

**To reproduce**
This can be reproduced in the `hello-react-native` app.
1. Add some logging before/after the `await client.configure(config, user);` call
2. Go offline (eg. for easy replication in iOS simulator, turn computer's Wifi/ethernet off)
3. Launch the app
4. The logging before configure shows, but not the logging after nor in the catch

**Expected behavior**
Expect `configure` to either return or throw an error.

**SDK version**
Tested on 4.2.1 (our app) and 4.2.0 (hello-react-native)

**Language version, developer tools**
Node 4.15.0, TypeScript 4.2.4

**OS/platform**
iOS 12.4

**Comment by bwoskow-ld** [comment]
Hi @haakandev,

Thanks for the bug report and the steps to reproduce it. We'll take a look at this. You mentioned using the iOS simulator for easy replication -- has this bug been limited to iOS?

Cheers,
@bwoskow-ld 

_Filed internally as 119718._

**Comment by haakandev** [comment]
Thanks @bwoskow-ld 
Gave Android a spin today on real device (emulator seems to disconnect metro if putting airplane mode on 😓 ) and it seems to work fine there - configuring returns even if device is offline.

**Comment by haakandev** [comment]
Hi @bwoskow-ld - happy holidays!
Just wanted to check in if you have a rough idea when you might get time to investigate/fix this?

**Comment by gwhelanLD** [comment]
Hi @haakandev,

We've taken a look at this and identified that there's an underlying difference in the behavior of the initialization when the device is known to be offline. We're planning on correcting this inconsistency within the iOS SDK and after that is released we will release a new `react-native-client-sdk` that uses the updated iOS SDK. One way to avoid awaiting the promise indefinitely if the device does not have a network connection would be to provide a `timeout` value to the `configure` method. We'd recommend providing a `timeout` regardless in case the network is non-functional in a way the underlying SDK cannot detect, but we are aware it's non-ideal to require waiting for the full `timeout` interval if we know the network is unavailable.

Thanks,
@gwhelanLD

*Filed Internally as `119718`*

**Comment by haakandev** [comment]
Hi @gwhelanLD and thanks for your answer.

Any idea when the iOS SDK might be updated with this fix?

In the meantime, we have added the optional timeout to the config arguments. Was initially trying with the `connectionTimeoutMillis` property on the first `config()` argument, but this didn't seem to do anything for the configuration timeout. Maybe consider making this clear in the documentation (and that the `timeout` argument is in seconds)?

Cheers,
Håkan

**Comment by kevindice** [comment]
This is still an issue for iOS while offline.

**Comment by louis-launchdarkly** [comment]
Hello @kevindice and @haakandev, can you check is this still an issue for the React Native 7.x release?

**Comment by kevindice** [comment]
> Hello @kevindice and @haakandev, can you check is this still an issue for the React Native 7.x release?

Sure thing - will take a look on Monday.

**Comment by kevindice** [comment]
Bump
