### ISSUE TITLE
How does the JavaScript point to native code without linking libraries?

### ISSUE THREAD

**Issue by alexpyoung** [launchdarkly/react-native-client-sdk#9]
**Describe the bug**
I am unable to run my own application after installing the SDK due to a null native module. Additionally, attempting to link the library results in build failures.

**To reproduce**
1. `git clone https://github.com/launchdarkly/hello-react-native.git`
2. `npm install`
3. `pushd ios && pod install && popd`
4. `react-native link launchdarkly-react-native-client-sdk`
5. `react-native run ios`

**Expected behavior**
I should be able to run the encapsulating application after installing the SDK with Cocoapods

**Logs**
<img width="644" alt="Screen Shot 2019-05-09 at 1 19 29 PM" src="https://user-images.githubusercontent.com/2624187/57473308-8aefb100-725d-11e9-890a-bad2f8fb54e5.png">

**SDK version**
`1.0.1`

**Language version, developer tools, OS/platform**
```
React Native Environment Info:
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 67.31 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.3 => 16.8.3
    react-native: 0.59.5 => 0.59.5
```

**Additional context**
Since this library relies on native code, I am curious how the JavaScript code knows where to look for the native interface without linking the library. I can successfully run the Hello application as is after an `npm install` and a `pod install`. However when I try to install the React Native SDK in my own application and run, I receive the `Native module cannot be null` error.

After linking the React Native SDK to try and mitigate this issue, in both my own project and the Hello project, I see the following errors:
```
❌  /Users/alex.young/q/mobile-dashboard/node_modules/launchdarkly-react-native-client-sdk/ios/../../../ios/Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstdarg:10:1: unknown type name 'namespace'

namespace std {
         ^

❌  /Users/alex.young/q/mobile-dashboard/node_modules/launchdarkly-react-native-client-sdk/ios/../../../ios/Pods/boost-for-react-native/boost/tr1/tr1/utility:21:20: 'utility' file not found
#     include_next <utility>
                ^

❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: could not build module 'Darwin'
#include <sys/types.h>
        ^

❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
        ^

❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/usr/include/objc/objc.h:31:10: could not build module 'Darwin'
#include <sys/types.h>      // for __DARWIN_NULL
         ^

❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/CoreServices.framework/Headers/UTCoreTypes.h:19:10: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
         ^

❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:9: could not build module 'Foundation'
#import <Foundation/Foundation.h>
        ^

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MBQ.xcworkspace
```

Here is my Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'MBQ' do
  use_frameworks!

  REACT_NATIVE = '../node_modules/react-native'

  pod 'yoga', path: "#{REACT_NATIVE}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: REACT_NATIVE, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies
  pod 'DoubleConversion', :podspec => "#{REACT_NATIVE}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{REACT_NATIVE}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{REACT_NATIVE}/third-party-podspecs/Folly.podspec"

  pod 'LaunchDarkly', :git => 'https://github.com/launchdarkly/ios-client-sdk.git', :tag => '3.0.0-beta.3'
  pod 'LaunchdarklyReactNativeClient', path: '../node_modules/launchdarkly-react-native-client-sdk/ios/'

  target 'MBQTests' do
    inherit! :search_paths
  end

end
```

**Comment by torchhound** [comment]
It looks like you're missing another linked library or you need to manually link the SDK. I've seen that type of error in development before and it's always been a missing linked library. You might be missing `Javascript.core`.

**Comment by alexpyoung** [comment]
@torchhound, the `react-native link launchdarkly-react-native-client-sdk` appears to be properly linking correctly in my own project, i.e. the project is embedded as a library and `libLaunchdarklyReactNativeClient.a` is linked. What was puzzling to me is that the Hello React Native project builds despite the [static library not being linked](https://github.com/launchdarkly/hello-react-native/blob/master/ios/HelloReactNative.xcodeproj/project.pbxproj#L366) and it's unclear to me why that is so. Is `react-native link` required for this SDK? As mentioned in the repro steps, I get the same errors in the Hello project after linking with the CLI.

I don't have any reason to suspect that other libraries have failed to link, since the symptoms only surface if I install the RN SDK pod or attempt to use the LD client at runtime.

**Comment by alexpyoung** [comment]
I'm not sure what was causing the original `Native module cannot be null`, but inherently it does not make sense to `link` libraries to your project that are already installed with Cocoapods. Cocopods encapsulates all dependencies in it's own framework that is already linked as part of `pod install`.

**Comment by Lohins** [comment]
Hi @alexpyoung Did you fix the `Native module cannot be null` issue? I have the same problem. I use cocoapods to install 
```
  pod 'LaunchDarkly', :git => 'https://github.com/launchdarkly/ios-client.git', :tag => '3.0.0-beta.3'
  pod 'LaunchdarklyReactNativeClient', path: rn_darkly_path
```
No manual linking. Then I got `Native module cannot be null` error. looks like the lib isn't linked correctly.
